// src/components/ViewListButton.vue
<template>
  <ActionButton
    title="View list"
    tooltipId="view-list"
    tooltip="View the list with all of the comments"
    :faIcon="faList"
  />
</template>

<script setup lang="ts">
import { faList } from "@fortawesome/free-solid-svg-icons";
import ActionButton from "./ActionButton.vue";
</script>

// src/components/ViewListButton.tsx
import {faList} from "@fortawesome/free-solid-svg-icons"
import ActionButton from "./ActionButton"

function ViewListButton() {
    return (
        <ActionButton
            title="View list"
            tooltipId="view-list"
            tooltip="View the list with all of the comments"
            faIcon={faList}
        />
    )
}

export default ViewListButton
